### ISSUE TITLE
W5500 with PiCorePlayer

### ISSUE THREAD

**Issue by dasfdlinux** [sonocotta/raspberry-media-center#4]
I have been attempting to use PiCorePlayer with the HiFi Raspberry Pi Media Center, and I am running into issues with the w5500 ethernet module not being detected. When I run ifconfig the only interface listed is lo. I added the overlays in /boot/config.txt as suggested in the getting started:
```
dtoverlay=gpio-ir,gpio_pin=23
dtoverlay=w5500
dtoverlay=hifiberry-dac
```
I'll look into some of the other recommended OS's soon, but I was hoping to use PiCorePlayer.

**Comment by anabolyc** [comment]
Hey @dasfdlinux . Thanks for bringing this issue. I tried it myself and failed as well. 

AFAIK PiCorePlayer uses kernel provided by Raspbian which is a good start, since it supports all the hardware. But it seems like most of the drivers are stripped out from the build to reduce the size. It should be fairly easy to change kernel config and rebuild with the w5500 support enabled but you'd need to access the PiCorePlayer build system. I failed to find one, may be I looked in the wrong place. Seems like PiCorePlayer folks decided not to open-source it and distribute firmware blobs instead. 

Again, I may be wrong, and if you could find the build scripts, I can try enabling missing hardware and rebuild the image.

**Comment by dasfdlinux** [comment]
Thank you for the time you spent on this. I'll see if I can find the build
system later when I get a chance. I forgot to mention it in the original
issue, but I did locate the w5500 overlay under /boot/overlays when I
downloaded the 32bit PiCotePlayer image, so I was hoping I had just missed
a step in applying the overlay.

**Comment by dasfdlinux** [comment]
I finally got the W5500 working with PiCorePlayer. I haven't applied the rotating MAC fix yet from your docs ([link](https://github.com/sonocotta/raspberry-media-center?tab=readme-ov-file#rotating-mac-address-on-the-w5500)), but maybe this solved issue will be useful for someone else.
https://github.com/piCorePlayer/pCP-Kernels/issues/9

**Comment by anabolyc** [comment]
Thanks @dasfdlinux that was not easy ;)
